2019-01-16 12:15:08,534 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-16 16:30:25,605 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-16 16:30:37,644 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-16 16:30:54,323 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 15:34:48,395 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 15:41:38,929 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 15:42:32,891 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 15:43:11,655 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 15:44:37,964 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 15:46:50,806 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 15:51:24,548 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 16:03:59,468 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 16:05:23,259 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 16:05:54,638 ERROR: Exception on /unfollow/susan [GET] [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/routes.py", line 127, in unfollow
    flash('You are not following {}').format(username)
AttributeError: 'NoneType' object has no attribute 'format'
2019-01-17 16:06:16,968 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 16:28:47,381 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 16:28:50,054 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 16:37:15,742 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 16:47:24,687 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 17:03:20,019 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 17:03:33,617 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:46]
2019-01-17 22:29:42,212 INFO: Microblog startup [in /Users/quinnangill/Desktop/Coding_Projects/flask/microblog/app/__init__.py:48]
2019-01-18 10:49:15,849 INFO: Microblog startup [in /Users/quinnangill/Desktop/flask_tutorial/microblog/app/__init__.py:48]
2019-01-18 11:09:28,365 INFO: Microblog startup [in /Users/quinnangill/Desktop/flask_tutorial/microblog/app/__init__.py:48]
2019-01-18 11:14:38,505 INFO: Microblog startup [in /Users/quinnangill/Desktop/flask_tutorial/microblog/app/__init__.py:48]
2019-01-18 11:14:44,421 INFO: Microblog startup [in /Users/quinnangill/Desktop/flask_tutorial/microblog/app/__init__.py:48]
2019-01-18 11:16:26,269 INFO: Microblog startup [in /Users/quinnangill/Desktop/flask_tutorial/microblog/app/__init__.py:48]
2019-01-18 12:42:25,818 INFO: Microblog startup [in /Users/quinnangill/Desktop/flask_tutorial/microblog/app/__init__.py:50]
2019-01-18 12:42:32,622 ERROR: Exception on /login [GET] [in /Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/app/routes.py", line 86, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/app/templates/base.html", line 46, in template
    {% block content %}
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/app/templates/base.html", line 46, in template
    {% block content %}
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/Users/quinnangill/Desktop/flask_tutorial/microblog/venv/lib/python3.7/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2019-01-18 12:43:17,414 INFO: Microblog startup [in /Users/quinnangill/Desktop/flask_tutorial/microblog/app/__init__.py:50]
